# Build workflow
# Builds the application for windows and ubuntu to test whether the latest commit builds or not.
name: build

on:
  push:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Write version file
        run: echo development > version.txt

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build Windows
        run: pyinstaller --clean --noconfirm specs/windows-terminservice.spec
      - name: Build Windows GUI
        run: pyinstaller --clean --noconfirm specs/windows-terminservice-gui.spec
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: Write version file
        run: echo development > version.txt

      - name: Print directory
        run: pwd

      - name: List directory
        run: ls -lah

      - name: print version file
        run: cat version.txt
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build Linux
        run: pyinstaller --clean --noconfirm specs/linux-64-terminservice.spec